shared:
  sample_rate: 48000

clap_config:
  model_name: "laion/clap-htsat-fused"
  batch_size: 32
  sample_pack_root: "/home/ec2-user/data/zippone/SampleToUse"
  reference_root: "/home/ec2-user/data/zippone/GM/GM_Mapped_Reduced"